# Databricks notebook source
# MAGIC %sql
# MAGIC USE CATALOG pricing_analytics;
# MAGIC
# MAGIC CREATE SCHEMA IF NOT EXISTS gold;
# MAGIC
# MAGIC USE SCHEMA gold;
# MAGIC
# MAGIC DROP TABLE IF  EXISTS REPORTING_DIM_DATE_GOLD; 
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS REPORTING_DIM_DATE_GOLD (
# MAGIC CALENDAR_DATE DATE,
# MAGIC DATE_ID BIGINT,
# MAGIC lakehouse_inserted_date TIMESTAMP,
# MAGIC lakehouse_updated_date TIMESTAMP
# MAGIC );
# MAGIC
# MAGIC DROP TABLE IF  EXISTS REPORTING_DIM_STATE_GOLD; 
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS REPORTING_DIM_STATE_GOLD (
# MAGIC STATE_NAME STRING,
# MAGIC STATE_ID BIGINT,
# MAGIC lakehouse_inserted_date TIMESTAMP,
# MAGIC lakehouse_updated_date TIMESTAMP
# MAGIC );
# MAGIC
# MAGIC DROP TABLE IF  EXISTS REPORTING_DIM_MARKET_GOLD; 
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS REPORTING_DIM_MARKET_GOLD (
# MAGIC MARKET_NAME STRING,
# MAGIC MARKET_ID BIGINT,
# MAGIC lakehouse_inserted_date TIMESTAMP,
# MAGIC lakehouse_updated_date TIMESTAMP
# MAGIC );
# MAGIC
# MAGIC DROP TABLE IF  EXISTS REPORTING_DIM_PRODUCT_GOLD; 
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS REPORTING_DIM_PRODUCT_GOLD (
# MAGIC PRODUCTGROUP_NAME STRING,
# MAGIC PRODUCT_NAME STRING,
# MAGIC PRODUCT_ID BIGINT,
# MAGIC lakehouse_inserted_date TIMESTAMP,
# MAGIC lakehouse_updated_date TIMESTAMP
# MAGIC );
# MAGIC
# MAGIC DROP TABLE IF  EXISTS REPORTING_DIM_VARIETY_GOLD; 
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS REPORTING_DIM_VARIETY_GOLD (
# MAGIC VARIETY STRING,
# MAGIC VARIETY_ID BIGINT,
# MAGIC lakehouse_inserted_date TIMESTAMP,
# MAGIC lakehouse_updated_date TIMESTAMP
# MAGIC );
# MAGIC
# MAGIC DROP TABLE IF  EXISTS REPORTING_FACT_DAILY_PRICING_GOLD; 
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS REPORTING_FACT_DAILY_PRICING_GOLD (
# MAGIC DATE_ID BIGINT,
# MAGIC STATE_ID BIGINT,
# MAGIC MARKET_ID BIGINT,
# MAGIC PRODUCT_ID BIGINT,
# MAGIC VARIETY_ID BIGINT,
# MAGIC ROW_ID BIGINT,
# MAGIC ARRIVAL_IN_TONNES DECIMAL(18,2),
# MAGIC MINIMUM_PRICE DECIMAL(36,2),
# MAGIC MAXIMUM_PRICE DECIMAL(36,2),
# MAGIC MODAL_PRICE DECIMAL(36,2),
# MAGIC lakehouse_inserted_date TIMESTAMP,
# MAGIC lakehouse_updated_date TIMESTAMP
# MAGIC );
# MAGIC
# MAGIC
# MAGIC

# COMMAND ----------

